spec:
  template:
    spec:
      containers:
      - imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "386Mi"
      imagePullSecrets:
      - name: docker-io